---
title: "Directors H-Index"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
Flix_data <- read_csv(here("Final_Project_FlixGem.csv"), col_names=TRUE)
Flix_data <- filter(Flix_data, `Series or Movie`== "Movie") %>% na.omit() %>% mutate(Runtime= fct_relevel(Runtime, c("< 30 minutes", "1-2 hour", "> 2 hrs")))
```

``` {r H-index for directors}
Flix_data <- separate_rows(Flix_data, Director, sep= ",") %>% group_by(Director) %>% select(Director, `Hidden Gem Score`)

H_index <- function(gem_scores) {
  gem_scores <- sort(gem_scores, decreasing=TRUE)
  num_movies <- length(gem_scores)
  h <- 0

  for (i in gem_scores) {
    if (i > h) {
      h <- h + 1
    } else {
      break
    }
  }
  h
}

top_directors<- Flix_data %>% summarize(H_index= H_index(`Hidden Gem Score`))

# top 10 directors
top_directors[order(top_directors$H_index, decreasing=TRUE), c(1,2)] %>% slice(1:10)

# top 10 directors with tied positions (resolved equalities)
top_directors[order(top_directors$H_index, decreasing=TRUE), c(1,2)] %>% filter(H_index >= 4)
```

