---
title: "HGS Regression Tree"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(rpart)
library(rpart.plot)
Flix_data <- read_csv(here("Final_Project_FlixGem.csv"), col_names=TRUE)
Flix_data <- filter(Flix_data, `Series or Movie`== "Movie") %>% na.omit() %>% mutate(Runtime= fct_relevel(Runtime, c("< 30 minutes", "1-2 hour", "> 2 hrs")))
```

```{r HGS Regression Tree}
Flix_data <- Flix_data %>% select(Languages, `Hidden Gem Score`, Runtime, `IMDb Score`,`Metacritic Score`,  `Rotten Tomatoes Score`)
Flix_lang_sep <- separate_rows(Flix_data, Languages, sep=",")
Flix_data_score <- Flix_data %>% select(`Hidden Gem Score`, Runtime, `IMDb Score`,`Metacritic Score`,  `Rotten Tomatoes Score`)

reg_tree_1 <- rpart(
  formula = `Hidden Gem Score` ~ .,
  data = Flix_data,
  method = "anova"
)

reg_tree_2 <- rpart(
  formula = `Hidden Gem Score` ~ .,
  data = Flix_lang_sep,
  method = "anova"
)


reg_tree_3 <- rpart(
  formula = `Hidden Gem Score` ~ .,
  data = Flix_data_score,
  method = "anova"
)
rpart.plot(reg_tree_1, main = "Figure 1: Regression Tree (multiple lang per movie)")
rpart.plot(reg_tree_2, main = "Figure 2: Regression Tree (grouped by languages)")
rpart.plot(reg_tree_3, main = "Figure 3: Regression Tree (without languages)")
```
